name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main # Trigger on pushes to the main

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.0 # Use the latest stable version
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            cd /root/ # Or /var/www/ if that's where you manage your web apps
            git clone git@github.com:5A681/profile.git
            cd profile

            # Build and run Docker Compose services
            echo "Building and starting Docker Compose services..."
            docker compose up -d --build --force-recreate

            echo "Deployment to Droplet complete!"
