name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.0 # Use the latest stable version
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Deploy to Droplet
        run: ssh root@188.166.191.199
          git clone git@github.com:5A681/profile.git
          cd profile
          docker compose  up -d --build
          exit
